package com.dyjs.meeting.dao;

import java.io.Serializable;

public class RoomTypeDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type
     *
     * @mbggenerated
     */
    private String roomType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_name
     *
     * @mbggenerated
     */
    private String roomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_price
     *
     * @mbggenerated
     */
    private String roomPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.id
     *
     * @return the value of room_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.id
     *
     * @param id the value for room_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.room_type
     *
     * @return the value of room_type.room_type
     *
     * @mbggenerated
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.room_type
     *
     * @param roomType the value for room_type.room_type
     *
     * @mbggenerated
     */
    public void setRoomType(String roomType) {
        this.roomType = roomType == null ? null : roomType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.room_name
     *
     * @return the value of room_type.room_name
     *
     * @mbggenerated
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.room_name
     *
     * @param roomName the value for room_type.room_name
     *
     * @mbggenerated
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.room_price
     *
     * @return the value of room_type.room_price
     *
     * @mbggenerated
     */
    public String getRoomPrice() {
        return roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.room_price
     *
     * @param roomPrice the value for room_type.room_price
     *
     * @mbggenerated
     */
    public void setRoomPrice(String roomPrice) {
        this.roomPrice = roomPrice == null ? null : roomPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.img
     *
     * @return the value of room_type.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.img
     *
     * @param img the value for room_type.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roomType=").append(roomType);
        sb.append(", roomName=").append(roomName);
        sb.append(", roomPrice=").append(roomPrice);
        sb.append(", img=").append(img);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}