package com.dyjs.meeting.dao;

import java.io.Serializable;
import java.util.Date;

public class Seat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_table.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_table.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_table.seatNo
     *
     * @mbggenerated
     */
    private String seatno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_table.creatTime
     *
     * @mbggenerated
     */
    private Date creattime;

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seat_table
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_table.id
     *
     * @return the value of seat_table.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_table.id
     *
     * @param id the value for seat_table.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_table.tel
     *
     * @return the value of seat_table.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_table.tel
     *
     * @param tel the value for seat_table.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_table.seatNo
     *
     * @return the value of seat_table.seatNo
     *
     * @mbggenerated
     */
    public String getSeatno() {
        return seatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_table.seatNo
     *
     * @param seatno the value for seat_table.seatNo
     *
     * @mbggenerated
     */
    public void setSeatno(String seatno) {
        this.seatno = seatno == null ? null : seatno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_table.creatTime
     *
     * @return the value of seat_table.creatTime
     *
     * @mbggenerated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_table.creatTime
     *
     * @param creattime the value for seat_table.creatTime
     *
     * @mbggenerated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_table
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tel=").append(tel);
        sb.append(", seatno=").append(seatno);
        sb.append(", creattime=").append(creattime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}