package com.dyjs.meeting.mapper;

import com.dyjs.meeting.dao.QrCodeDto;

public interface QrCodeDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated
     */
    int insert(QrCodeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated
     */
    int insertSelective(QrCodeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated
     */
    QrCodeDto selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrCodeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QrCodeDto record);

    void deleteByTel(String tel);

    QrCodeDto selectByTel(String tel);
}