package com.dyjs.meeting.mapper;

import com.dyjs.meeting.dao.RoomTypeDto;

public interface RoomTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int insert(RoomTypeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int insertSelective(RoomTypeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    RoomTypeDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomTypeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomTypeDto record);
}