package com.dyzhsw.cardcontrol.dto;

import java.io.Serializable;
import java.util.Date;

public class Configuration implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.id
     *
     * @mbggenerated
     */
    private String id;

    private String resolve;

    public String getResolve() {
        return resolve;
    }

    public void setResolve(String resolve) {
        this.resolve = resolve;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.telemetryAddress
     *
     * @mbggenerated
     */
    private String telemetryaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.centerAdress
     *
     * @mbggenerated
     */
    private String centeradress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.functionCode
     *
     * @mbggenerated
     */
    private String functioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.sendTime
     *
     * @mbggenerated
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.centerAdress4
     *
     * @mbggenerated
     */
    private String centeradress4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.chanel1
     *
     * @mbggenerated
     */
    private String chanel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.chanel2
     *
     * @mbggenerated
     */
    private String chanel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.chanel3
     *
     * @mbggenerated
     */
    private String chanel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.chanel4
     *
     * @mbggenerated
     */
    private String chanel4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.workStyle
     *
     * @mbggenerated
     */
    private String workstyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.colletKey
     *
     * @mbggenerated
     */
    private String colletkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table configuration
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.id
     *
     * @return the value of configuration.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.id
     *
     * @param id the value for configuration.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.telemetryAddress
     *
     * @return the value of configuration.telemetryAddress
     *
     * @mbggenerated
     */
    public String getTelemetryaddress() {
        return telemetryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.telemetryAddress
     *
     * @param telemetryaddress the value for configuration.telemetryAddress
     *
     * @mbggenerated
     */
    public void setTelemetryaddress(String telemetryaddress) {
        this.telemetryaddress = telemetryaddress == null ? null : telemetryaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.centerAdress
     *
     * @return the value of configuration.centerAdress
     *
     * @mbggenerated
     */
    public String getCenteradress() {
        return centeradress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.centerAdress
     *
     * @param centeradress the value for configuration.centerAdress
     *
     * @mbggenerated
     */
    public void setCenteradress(String centeradress) {
        this.centeradress = centeradress == null ? null : centeradress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.password
     *
     * @return the value of configuration.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.password
     *
     * @param password the value for configuration.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.flag
     *
     * @return the value of configuration.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.flag
     *
     * @param flag the value for configuration.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.functionCode
     *
     * @return the value of configuration.functionCode
     *
     * @mbggenerated
     */
    public String getFunctioncode() {
        return functioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.functionCode
     *
     * @param functioncode the value for configuration.functionCode
     *
     * @mbggenerated
     */
    public void setFunctioncode(String functioncode) {
        this.functioncode = functioncode == null ? null : functioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.sendTime
     *
     * @return the value of configuration.sendTime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.sendTime
     *
     * @param sendtime the value for configuration.sendTime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.centerAdress4
     *
     * @return the value of configuration.centerAdress4
     *
     * @mbggenerated
     */
    public String getCenteradress4() {
        return centeradress4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.centerAdress4
     *
     * @param centeradress4 the value for configuration.centerAdress4
     *
     * @mbggenerated
     */
    public void setCenteradress4(String centeradress4) {
        this.centeradress4 = centeradress4 == null ? null : centeradress4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.chanel1
     *
     * @return the value of configuration.chanel1
     *
     * @mbggenerated
     */
    public String getChanel1() {
        return chanel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.chanel1
     *
     * @param chanel1 the value for configuration.chanel1
     *
     * @mbggenerated
     */
    public void setChanel1(String chanel1) {
        this.chanel1 = chanel1 == null ? null : chanel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.chanel2
     *
     * @return the value of configuration.chanel2
     *
     * @mbggenerated
     */
    public String getChanel2() {
        return chanel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.chanel2
     *
     * @param chanel2 the value for configuration.chanel2
     *
     * @mbggenerated
     */
    public void setChanel2(String chanel2) {
        this.chanel2 = chanel2 == null ? null : chanel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.chanel3
     *
     * @return the value of configuration.chanel3
     *
     * @mbggenerated
     */
    public String getChanel3() {
        return chanel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.chanel3
     *
     * @param chanel3 the value for configuration.chanel3
     *
     * @mbggenerated
     */
    public void setChanel3(String chanel3) {
        this.chanel3 = chanel3 == null ? null : chanel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.chanel4
     *
     * @return the value of configuration.chanel4
     *
     * @mbggenerated
     */
    public String getChanel4() {
        return chanel4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.chanel4
     *
     * @param chanel4 the value for configuration.chanel4
     *
     * @mbggenerated
     */
    public void setChanel4(String chanel4) {
        this.chanel4 = chanel4 == null ? null : chanel4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.workStyle
     *
     * @return the value of configuration.workStyle
     *
     * @mbggenerated
     */
    public String getWorkstyle() {
        return workstyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.workStyle
     *
     * @param workstyle the value for configuration.workStyle
     *
     * @mbggenerated
     */
    public void setWorkstyle(String workstyle) {
        this.workstyle = workstyle == null ? null : workstyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.colletKey
     *
     * @return the value of configuration.colletKey
     *
     * @mbggenerated
     */
    public String getColletkey() {
        return colletkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.colletKey
     *
     * @param colletkey the value for configuration.colletKey
     *
     * @mbggenerated
     */
    public void setColletkey(String colletkey) {
        this.colletkey = colletkey == null ? null : colletkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.createTime
     *
     * @return the value of configuration.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.createTime
     *
     * @param createtime the value for configuration.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", telemetryaddress=").append(telemetryaddress);
        sb.append(", centeradress=").append(centeradress);
        sb.append(", password=").append(password);
        sb.append(", flag=").append(flag);
        sb.append(", functioncode=").append(functioncode);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", centeradress4=").append(centeradress4);
        sb.append(", chanel1=").append(chanel1);
        sb.append(", chanel2=").append(chanel2);
        sb.append(", chanel3=").append(chanel3);
        sb.append(", chanel4=").append(chanel4);
        sb.append(", workstyle=").append(workstyle);
        sb.append(", colletkey=").append(colletkey);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}