package com.dyzhsw.cardcontrol.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class equipment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.telemetryAddress
     *
     * @mbggenerated
     */
    private String telemetryaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.centerAdress4
     *
     * @mbggenerated
     */
    private String centeradress4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.centerAdress
     *
     * @mbggenerated
     */
    private String centeradress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.isOnlie
     *
     * @mbggenerated
     */
    private String isonlie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.createTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern ="yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.updateTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern ="yyyy-MM-dd HH:mm:ss")
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.channel1
     *
     * @mbggenerated
     */
    private String channel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.channel2
     *
     * @mbggenerated
     */
    private String channel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.channel3
     *
     * @mbggenerated
     */
    private String channel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.channel4
     *
     * @mbggenerated
     */
    private String channel4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.workStyle
     *
     * @mbggenerated
     */
    private String workstyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.colletKey
     *
     * @mbggenerated
     */
    private String colletkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.id
     *
     * @return the value of equipment_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.id
     *
     * @param id the value for equipment_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.telemetryAddress
     *
     * @return the value of equipment_info.telemetryAddress
     *
     * @mbggenerated
     */
    public String getTelemetryaddress() {
        return telemetryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.telemetryAddress
     *
     * @param telemetryaddress the value for equipment_info.telemetryAddress
     *
     * @mbggenerated
     */
    public void setTelemetryaddress(String telemetryaddress) {
        this.telemetryaddress = telemetryaddress == null ? null : telemetryaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.centerAdress4
     *
     * @return the value of equipment_info.centerAdress4
     *
     * @mbggenerated
     */
    public String getCenteradress4() {
        return centeradress4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.centerAdress4
     *
     * @param centeradress4 the value for equipment_info.centerAdress4
     *
     * @mbggenerated
     */
    public void setCenteradress4(String centeradress4) {
        this.centeradress4 = centeradress4 == null ? null : centeradress4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.centerAdress
     *
     * @return the value of equipment_info.centerAdress
     *
     * @mbggenerated
     */
    public String getCenteradress() {
        return centeradress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.centerAdress
     *
     * @param centeradress the value for equipment_info.centerAdress
     *
     * @mbggenerated
     */
    public void setCenteradress(String centeradress) {
        this.centeradress = centeradress == null ? null : centeradress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.channel
     *
     * @return the value of equipment_info.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.channel
     *
     * @param channel the value for equipment_info.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.password
     *
     * @return the value of equipment_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.password
     *
     * @param password the value for equipment_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.isOnlie
     *
     * @return the value of equipment_info.isOnlie
     *
     * @mbggenerated
     */
    public String getIsonlie() {
        return isonlie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.isOnlie
     *
     * @param isonlie the value for equipment_info.isOnlie
     *
     * @mbggenerated
     */
    public void setIsonlie(String isonlie) {
        this.isonlie = isonlie == null ? null : isonlie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.createTime
     *
     * @return the value of equipment_info.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.createTime
     *
     * @param createtime the value for equipment_info.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.updateTime
     *
     * @return the value of equipment_info.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.updateTime
     *
     * @param updatetime the value for equipment_info.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.channel1
     *
     * @return the value of equipment_info.channel1
     *
     * @mbggenerated
     */
    public String getChannel1() {
        return channel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.channel1
     *
     * @param channel1 the value for equipment_info.channel1
     *
     * @mbggenerated
     */
    public void setChannel1(String channel1) {
        this.channel1 = channel1 == null ? null : channel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.channel2
     *
     * @return the value of equipment_info.channel2
     *
     * @mbggenerated
     */
    public String getChannel2() {
        return channel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.channel2
     *
     * @param channel2 the value for equipment_info.channel2
     *
     * @mbggenerated
     */
    public void setChannel2(String channel2) {
        this.channel2 = channel2 == null ? null : channel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.channel3
     *
     * @return the value of equipment_info.channel3
     *
     * @mbggenerated
     */
    public String getChannel3() {
        return channel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.channel3
     *
     * @param channel3 the value for equipment_info.channel3
     *
     * @mbggenerated
     */
    public void setChannel3(String channel3) {
        this.channel3 = channel3 == null ? null : channel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.channel4
     *
     * @return the value of equipment_info.channel4
     *
     * @mbggenerated
     */
    public String getChannel4() {
        return channel4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.channel4
     *
     * @param channel4 the value for equipment_info.channel4
     *
     * @mbggenerated
     */
    public void setChannel4(String channel4) {
        this.channel4 = channel4 == null ? null : channel4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.workStyle
     *
     * @return the value of equipment_info.workStyle
     *
     * @mbggenerated
     */
    public String getWorkstyle() {
        return workstyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.workStyle
     *
     * @param workstyle the value for equipment_info.workStyle
     *
     * @mbggenerated
     */
    public void setWorkstyle(String workstyle) {
        this.workstyle = workstyle == null ? null : workstyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.colletKey
     *
     * @return the value of equipment_info.colletKey
     *
     * @mbggenerated
     */
    public String getColletkey() {
        return colletkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.colletKey
     *
     * @param colletkey the value for equipment_info.colletKey
     *
     * @mbggenerated
     */
    public void setColletkey(String colletkey) {
        this.colletkey = colletkey == null ? null : colletkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", telemetryaddress=").append(telemetryaddress);
        sb.append(", centeradress4=").append(centeradress4);
        sb.append(", centeradress=").append(centeradress);
        sb.append(", channel=").append(channel);
        sb.append(", password=").append(password);
        sb.append(", isonlie=").append(isonlie);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", channel1=").append(channel1);
        sb.append(", channel2=").append(channel2);
        sb.append(", channel3=").append(channel3);
        sb.append(", channel4=").append(channel4);
        sb.append(", workstyle=").append(workstyle);
        sb.append(", colletkey=").append(colletkey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}