package com.dyzhsw.cardcontrol.dto;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class StationClock implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_clock.id
     *
     * @mbggenerated
     */
    private String id;

    private String resolve;

    public String getResolve() {
        return resolve;
    }

    public void setResolve(String resolve) {
        this.resolve = resolve;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_clock.centerAdress
     *
     * @mbggenerated
     */
    private String centeradress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_clock.telemetryAddress
     *
     * @mbggenerated
     */
    private String telemetryaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_clock.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_clock.fuctionCode
     *
     * @mbggenerated
     */
    private String fuctioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_clock.serialNumber
     *
     * @mbggenerated
     */
    private String serialnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_clock.sendTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_clock.createTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table telemetry_station_clock
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_clock.id
     *
     * @return the value of telemetry_station_clock.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_clock.id
     *
     * @param id the value for telemetry_station_clock.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_clock.centerAdress
     *
     * @return the value of telemetry_station_clock.centerAdress
     *
     * @mbggenerated
     */
    public String getCenteradress() {
        return centeradress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_clock.centerAdress
     *
     * @param centeradress the value for telemetry_station_clock.centerAdress
     *
     * @mbggenerated
     */
    public void setCenteradress(String centeradress) {
        this.centeradress = centeradress == null ? null : centeradress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_clock.telemetryAddress
     *
     * @return the value of telemetry_station_clock.telemetryAddress
     *
     * @mbggenerated
     */
    public String getTelemetryaddress() {
        return telemetryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_clock.telemetryAddress
     *
     * @param telemetryaddress the value for telemetry_station_clock.telemetryAddress
     *
     * @mbggenerated
     */
    public void setTelemetryaddress(String telemetryaddress) {
        this.telemetryaddress = telemetryaddress == null ? null : telemetryaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_clock.password
     *
     * @return the value of telemetry_station_clock.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_clock.password
     *
     * @param password the value for telemetry_station_clock.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_clock.fuctionCode
     *
     * @return the value of telemetry_station_clock.fuctionCode
     *
     * @mbggenerated
     */
    public String getFuctioncode() {
        return fuctioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_clock.fuctionCode
     *
     * @param fuctioncode the value for telemetry_station_clock.fuctionCode
     *
     * @mbggenerated
     */
    public void setFuctioncode(String fuctioncode) {
        this.fuctioncode = fuctioncode == null ? null : fuctioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_clock.serialNumber
     *
     * @return the value of telemetry_station_clock.serialNumber
     *
     * @mbggenerated
     */
    public String getSerialnumber() {
        return serialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_clock.serialNumber
     *
     * @param serialnumber the value for telemetry_station_clock.serialNumber
     *
     * @mbggenerated
     */
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber == null ? null : serialnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_clock.sendTime
     *
     * @return the value of telemetry_station_clock.sendTime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_clock.sendTime
     *
     * @param sendtime the value for telemetry_station_clock.sendTime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_clock.createTime
     *
     * @return the value of telemetry_station_clock.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_clock.createTime
     *
     * @param createtime the value for telemetry_station_clock.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_clock
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", centeradress=").append(centeradress);
        sb.append(", telemetryaddress=").append(telemetryaddress);
        sb.append(", password=").append(password);
        sb.append(", fuctioncode=").append(fuctioncode);
        sb.append(", serialnumber=").append(serialnumber);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}