package com.dyzhsw.cardcontrol.dto;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class StationTime implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.telemetryAddress
     *
     * @mbggenerated
     */
    private String telemetryaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.centerAdress
     *
     * @mbggenerated
     */
    private String centeradress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.serialNumber
     *
     * @mbggenerated
     */
    private String serialnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.fuctionCode
     *
     * @mbggenerated
     */
    private String fuctioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.sendTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.createTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.typeCode
     *
     * @mbggenerated
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.observationTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date observationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.instantaneousFlowRate
     *
     * @mbggenerated
     */
    private String instantaneousflowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.cumulativeFlowRate
     *
     * @mbggenerated
     */
    private String cumulativeflowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.cumulativeElectricityRate
     *
     * @mbggenerated
     */
    private String cumulativeelectricityrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.cumulativeTime
     *
     * @mbggenerated
     */
    private String cumulativetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.voltage
     *
     * @mbggenerated
     */
    private String voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.voltageA
     *
     * @mbggenerated
     */
    private String voltagea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.voltageB
     *
     * @mbggenerated
     */
    private String voltageb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.voltageC
     *
     * @mbggenerated
     */
    private String voltagec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.electricA
     *
     * @mbggenerated
     */
    private String electrica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.electricB
     *
     * @mbggenerated
     */
    private String electricb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.electricC
     *
     * @mbggenerated
     */
    private String electricc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.status
     *
     * @mbggenerated
     */
    private String status;

    private TelemetryState telemetryState;

    public TelemetryState getTelemetryState() {
        return telemetryState;
    }

    public void setTelemetryState(TelemetryState telemetryState) {
        this.telemetryState = telemetryState;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_station_time.csqSignalIntensity
     *
     * @mbggenerated
     */
    private String csqsignalintensity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table telemetry_station_time
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.id
     *
     * @return the value of telemetry_station_time.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.id
     *
     * @param id the value for telemetry_station_time.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.telemetryAddress
     *
     * @return the value of telemetry_station_time.telemetryAddress
     *
     * @mbggenerated
     */
    public String getTelemetryaddress() {
        return telemetryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.telemetryAddress
     *
     * @param telemetryaddress the value for telemetry_station_time.telemetryAddress
     *
     * @mbggenerated
     */
    public void setTelemetryaddress(String telemetryaddress) {
        this.telemetryaddress = telemetryaddress == null ? null : telemetryaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.centerAdress
     *
     * @return the value of telemetry_station_time.centerAdress
     *
     * @mbggenerated
     */
    public String getCenteradress() {
        return centeradress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.centerAdress
     *
     * @param centeradress the value for telemetry_station_time.centerAdress
     *
     * @mbggenerated
     */
    public void setCenteradress(String centeradress) {
        this.centeradress = centeradress == null ? null : centeradress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.password
     *
     * @return the value of telemetry_station_time.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.password
     *
     * @param password the value for telemetry_station_time.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.serialNumber
     *
     * @return the value of telemetry_station_time.serialNumber
     *
     * @mbggenerated
     */
    public String getSerialnumber() {
        return serialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.serialNumber
     *
     * @param serialnumber the value for telemetry_station_time.serialNumber
     *
     * @mbggenerated
     */
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber == null ? null : serialnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.fuctionCode
     *
     * @return the value of telemetry_station_time.fuctionCode
     *
     * @mbggenerated
     */
    public String getFuctioncode() {
        return fuctioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.fuctionCode
     *
     * @param fuctioncode the value for telemetry_station_time.fuctionCode
     *
     * @mbggenerated
     */
    public void setFuctioncode(String fuctioncode) {
        this.fuctioncode = fuctioncode == null ? null : fuctioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.sendTime
     *
     * @return the value of telemetry_station_time.sendTime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.sendTime
     *
     * @param sendtime the value for telemetry_station_time.sendTime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.createTime
     *
     * @return the value of telemetry_station_time.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.createTime
     *
     * @param createtime the value for telemetry_station_time.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.typeCode
     *
     * @return the value of telemetry_station_time.typeCode
     *
     * @mbggenerated
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.typeCode
     *
     * @param typecode the value for telemetry_station_time.typeCode
     *
     * @mbggenerated
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.observationTime
     *
     * @return the value of telemetry_station_time.observationTime
     *
     * @mbggenerated
     */
    public Date getObservationtime() {
        return observationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.observationTime
     *
     * @param observationtime the value for telemetry_station_time.observationTime
     *
     * @mbggenerated
     */
    public void setObservationtime(Date observationtime) {
        this.observationtime = observationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.instantaneousFlowRate
     *
     * @return the value of telemetry_station_time.instantaneousFlowRate
     *
     * @mbggenerated
     */
    public String getInstantaneousflowrate() {
        return instantaneousflowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.instantaneousFlowRate
     *
     * @param instantaneousflowrate the value for telemetry_station_time.instantaneousFlowRate
     *
     * @mbggenerated
     */
    public void setInstantaneousflowrate(String instantaneousflowrate) {
        this.instantaneousflowrate = instantaneousflowrate == null ? null : instantaneousflowrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.cumulativeFlowRate
     *
     * @return the value of telemetry_station_time.cumulativeFlowRate
     *
     * @mbggenerated
     */
    public String getCumulativeflowrate() {
        return cumulativeflowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.cumulativeFlowRate
     *
     * @param cumulativeflowrate the value for telemetry_station_time.cumulativeFlowRate
     *
     * @mbggenerated
     */
    public void setCumulativeflowrate(String cumulativeflowrate) {
        this.cumulativeflowrate = cumulativeflowrate == null ? null : cumulativeflowrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.cumulativeElectricityRate
     *
     * @return the value of telemetry_station_time.cumulativeElectricityRate
     *
     * @mbggenerated
     */
    public String getCumulativeelectricityrate() {
        return cumulativeelectricityrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.cumulativeElectricityRate
     *
     * @param cumulativeelectricityrate the value for telemetry_station_time.cumulativeElectricityRate
     *
     * @mbggenerated
     */
    public void setCumulativeelectricityrate(String cumulativeelectricityrate) {
        this.cumulativeelectricityrate = cumulativeelectricityrate == null ? null : cumulativeelectricityrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.cumulativeTime
     *
     * @return the value of telemetry_station_time.cumulativeTime
     *
     * @mbggenerated
     */
    public String getCumulativetime() {
        return cumulativetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.cumulativeTime
     *
     * @param cumulativetime the value for telemetry_station_time.cumulativeTime
     *
     * @mbggenerated
     */
    public void setCumulativetime(String cumulativetime) {
        this.cumulativetime = cumulativetime == null ? null : cumulativetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.voltage
     *
     * @return the value of telemetry_station_time.voltage
     *
     * @mbggenerated
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.voltage
     *
     * @param voltage the value for telemetry_station_time.voltage
     *
     * @mbggenerated
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage == null ? null : voltage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.voltageA
     *
     * @return the value of telemetry_station_time.voltageA
     *
     * @mbggenerated
     */
    public String getVoltagea() {
        return voltagea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.voltageA
     *
     * @param voltagea the value for telemetry_station_time.voltageA
     *
     * @mbggenerated
     */
    public void setVoltagea(String voltagea) {
        this.voltagea = voltagea == null ? null : voltagea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.voltageB
     *
     * @return the value of telemetry_station_time.voltageB
     *
     * @mbggenerated
     */
    public String getVoltageb() {
        return voltageb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.voltageB
     *
     * @param voltageb the value for telemetry_station_time.voltageB
     *
     * @mbggenerated
     */
    public void setVoltageb(String voltageb) {
        this.voltageb = voltageb == null ? null : voltageb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.voltageC
     *
     * @return the value of telemetry_station_time.voltageC
     *
     * @mbggenerated
     */
    public String getVoltagec() {
        return voltagec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.voltageC
     *
     * @param voltagec the value for telemetry_station_time.voltageC
     *
     * @mbggenerated
     */
    public void setVoltagec(String voltagec) {
        this.voltagec = voltagec == null ? null : voltagec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.electricA
     *
     * @return the value of telemetry_station_time.electricA
     *
     * @mbggenerated
     */
    public String getElectrica() {
        return electrica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.electricA
     *
     * @param electrica the value for telemetry_station_time.electricA
     *
     * @mbggenerated
     */
    public void setElectrica(String electrica) {
        this.electrica = electrica == null ? null : electrica.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.electricB
     *
     * @return the value of telemetry_station_time.electricB
     *
     * @mbggenerated
     */
    public String getElectricb() {
        return electricb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.electricB
     *
     * @param electricb the value for telemetry_station_time.electricB
     *
     * @mbggenerated
     */
    public void setElectricb(String electricb) {
        this.electricb = electricb == null ? null : electricb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.electricC
     *
     * @return the value of telemetry_station_time.electricC
     *
     * @mbggenerated
     */
    public String getElectricc() {
        return electricc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.electricC
     *
     * @param electricc the value for telemetry_station_time.electricC
     *
     * @mbggenerated
     */
    public void setElectricc(String electricc) {
        this.electricc = electricc == null ? null : electricc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.status
     *
     * @return the value of telemetry_station_time.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.status
     *
     * @param status the value for telemetry_station_time.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_station_time.csqSignalIntensity
     *
     * @return the value of telemetry_station_time.csqSignalIntensity
     *
     * @mbggenerated
     */
    public String getCsqsignalintensity() {
        return csqsignalintensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_station_time.csqSignalIntensity
     *
     * @param csqsignalintensity the value for telemetry_station_time.csqSignalIntensity
     *
     * @mbggenerated
     */
    public void setCsqsignalintensity(String csqsignalintensity) {
        this.csqsignalintensity = csqsignalintensity == null ? null : csqsignalintensity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_time
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", telemetryaddress=").append(telemetryaddress);
        sb.append(", centeradress=").append(centeradress);
        sb.append(", password=").append(password);
        sb.append(", serialnumber=").append(serialnumber);
        sb.append(", fuctioncode=").append(fuctioncode);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", createtime=").append(createtime);
        sb.append(", typecode=").append(typecode);
        sb.append(", observationtime=").append(observationtime);
        sb.append(", instantaneousflowrate=").append(instantaneousflowrate);
        sb.append(", cumulativeflowrate=").append(cumulativeflowrate);
        sb.append(", cumulativeelectricityrate=").append(cumulativeelectricityrate);
        sb.append(", cumulativetime=").append(cumulativetime);
        sb.append(", voltage=").append(voltage);
        sb.append(", voltagea=").append(voltagea);
        sb.append(", voltageb=").append(voltageb);
        sb.append(", voltagec=").append(voltagec);
        sb.append(", electrica=").append(electrica);
        sb.append(", electricb=").append(electricb);
        sb.append(", electricc=").append(electricc);
        sb.append(", status=").append(status);
        sb.append(", csqsignalintensity=").append(csqsignalintensity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    private String resolve;

    public String getResolve() {
        return resolve;
    }

    public void setResolve(String resolve) {
        this.resolve = resolve;
    }
}