package com.dyzhsw.cardcontrol.dto;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class SwitchPump implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.id
     *
     * @mbggenerated
     */
    private String id;

    private String cumulativeTime;

    private String voltage;

    private String csqSignalIntensity;

    private String resolve;

    public String getResolve() {
        return resolve;
    }

    public void setResolve(String resolve) {
        this.resolve = resolve;
    }

    public String getCumulativeTime() {
        return cumulativeTime;
    }

    public void setCumulativeTime(String cumulativeTime) {
        this.cumulativeTime = cumulativeTime;
    }

    public String getVoltage() {
        return voltage;
    }

    public void setVoltage(String voltage) {
        this.voltage = voltage;
    }

    public String getCsqSignalIntensity() {
        return csqSignalIntensity;
    }

    public void setCsqSignalIntensity(String csqSignalIntensity) {
        this.csqSignalIntensity = csqSignalIntensity;
    }

    public String getInstantaneousFlowRate() {
        return instantaneousFlowRate;
    }

    public void setInstantaneousFlowRate(String instantaneousFlowRate) {
        this.instantaneousFlowRate = instantaneousFlowRate;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    private String instantaneousFlowRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.telemetryAddress
     *
     * @mbggenerated
     */
    private String telemetryaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.centerAdress
     *
     * @mbggenerated
     */
    private String centeradress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.serialNumber
     *
     * @mbggenerated
     */
    private String serialnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.fuctionCode
     *
     * @mbggenerated
     */
    private String fuctioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.sendTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.typeCode
     *
     * @mbggenerated
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.observationTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date observationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.status
     *
     * @mbggenerated
     */
    private String status;

    private TelemetryState telemetryState;

    public TelemetryState getTelemetryState() {
        return telemetryState;
    }

    public void setTelemetryState(TelemetryState telemetryState) {
        this.telemetryState = telemetryState;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.cumulativeFlowRate
     *
     * @mbggenerated
     */
    private String cumulativeflowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.cumulativeElectricityRate
     *
     * @mbggenerated
     */
    private String cumulativeelectricityrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.voltageA
     *
     * @mbggenerated
     */
    private String voltagea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.voltageB
     *
     * @mbggenerated
     */
    private String voltageb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.voltageC
     *
     * @mbggenerated
     */
    private String voltagec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.electricA
     *
     * @mbggenerated
     */
    private String electrica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.electricB
     *
     * @mbggenerated
     */
    private String electricb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.electricC
     *
     * @mbggenerated
     */
    private String electricc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.userNumber
     *
     * @mbggenerated
     */
    private String usernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.icCard
     *
     * @mbggenerated
     */
    private String iccard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.balance
     *
     * @mbggenerated
     */
    private String balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.waterConsumption
     *
     * @mbggenerated
     */
    private String waterconsumption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.electricityConsumption
     *
     * @mbggenerated
     */
    private String electricityconsumption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.useTime
     *
     * @mbggenerated
     */
    private String usetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.startTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.endTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.consumption
     *
     * @mbggenerated
     */
    private String consumption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.comtrol
     *
     * @mbggenerated
     */
    private String comtrol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telemetry_switch_pump.createTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table telemetry_switch_pump
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.id
     *
     * @return the value of telemetry_switch_pump.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.id
     *
     * @param id the value for telemetry_switch_pump.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.telemetryAddress
     *
     * @return the value of telemetry_switch_pump.telemetryAddress
     *
     * @mbggenerated
     */
    public String getTelemetryaddress() {
        return telemetryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.telemetryAddress
     *
     * @param telemetryaddress the value for telemetry_switch_pump.telemetryAddress
     *
     * @mbggenerated
     */
    public void setTelemetryaddress(String telemetryaddress) {
        this.telemetryaddress = telemetryaddress == null ? null : telemetryaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.centerAdress
     *
     * @return the value of telemetry_switch_pump.centerAdress
     *
     * @mbggenerated
     */
    public String getCenteradress() {
        return centeradress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.centerAdress
     *
     * @param centeradress the value for telemetry_switch_pump.centerAdress
     *
     * @mbggenerated
     */
    public void setCenteradress(String centeradress) {
        this.centeradress = centeradress == null ? null : centeradress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.password
     *
     * @return the value of telemetry_switch_pump.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.password
     *
     * @param password the value for telemetry_switch_pump.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.serialNumber
     *
     * @return the value of telemetry_switch_pump.serialNumber
     *
     * @mbggenerated
     */
    public String getSerialnumber() {
        return serialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.serialNumber
     *
     * @param serialnumber the value for telemetry_switch_pump.serialNumber
     *
     * @mbggenerated
     */
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber == null ? null : serialnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.fuctionCode
     *
     * @return the value of telemetry_switch_pump.fuctionCode
     *
     * @mbggenerated
     */
    public String getFuctioncode() {
        return fuctioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.fuctionCode
     *
     * @param fuctioncode the value for telemetry_switch_pump.fuctionCode
     *
     * @mbggenerated
     */
    public void setFuctioncode(String fuctioncode) {
        this.fuctioncode = fuctioncode == null ? null : fuctioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.sendTime
     *
     * @return the value of telemetry_switch_pump.sendTime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.sendTime
     *
     * @param sendtime the value for telemetry_switch_pump.sendTime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.typeCode
     *
     * @return the value of telemetry_switch_pump.typeCode
     *
     * @mbggenerated
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.typeCode
     *
     * @param typecode the value for telemetry_switch_pump.typeCode
     *
     * @mbggenerated
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.observationTime
     *
     * @return the value of telemetry_switch_pump.observationTime
     *
     * @mbggenerated
     */
    public Date getObservationtime() {
        return observationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.observationTime
     *
     * @param observationtime the value for telemetry_switch_pump.observationTime
     *
     * @mbggenerated
     */
    public void setObservationtime(Date observationtime) {
        this.observationtime = observationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.status
     *
     * @return the value of telemetry_switch_pump.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.status
     *
     * @param status the value for telemetry_switch_pump.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.cumulativeFlowRate
     *
     * @return the value of telemetry_switch_pump.cumulativeFlowRate
     *
     * @mbggenerated
     */
    public String getCumulativeflowrate() {
        return cumulativeflowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.cumulativeFlowRate
     *
     * @param cumulativeflowrate the value for telemetry_switch_pump.cumulativeFlowRate
     *
     * @mbggenerated
     */
    public void setCumulativeflowrate(String cumulativeflowrate) {
        this.cumulativeflowrate = cumulativeflowrate == null ? null : cumulativeflowrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.cumulativeElectricityRate
     *
     * @return the value of telemetry_switch_pump.cumulativeElectricityRate
     *
     * @mbggenerated
     */
    public String getCumulativeelectricityrate() {
        return cumulativeelectricityrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.cumulativeElectricityRate
     *
     * @param cumulativeelectricityrate the value for telemetry_switch_pump.cumulativeElectricityRate
     *
     * @mbggenerated
     */
    public void setCumulativeelectricityrate(String cumulativeelectricityrate) {
        this.cumulativeelectricityrate = cumulativeelectricityrate == null ? null : cumulativeelectricityrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.voltageA
     *
     * @return the value of telemetry_switch_pump.voltageA
     *
     * @mbggenerated
     */
    public String getVoltagea() {
        return voltagea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.voltageA
     *
     * @param voltagea the value for telemetry_switch_pump.voltageA
     *
     * @mbggenerated
     */
    public void setVoltagea(String voltagea) {
        this.voltagea = voltagea == null ? null : voltagea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.voltageB
     *
     * @return the value of telemetry_switch_pump.voltageB
     *
     * @mbggenerated
     */
    public String getVoltageb() {
        return voltageb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.voltageB
     *
     * @param voltageb the value for telemetry_switch_pump.voltageB
     *
     * @mbggenerated
     */
    public void setVoltageb(String voltageb) {
        this.voltageb = voltageb == null ? null : voltageb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.voltageC
     *
     * @return the value of telemetry_switch_pump.voltageC
     *
     * @mbggenerated
     */
    public String getVoltagec() {
        return voltagec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.voltageC
     *
     * @param voltagec the value for telemetry_switch_pump.voltageC
     *
     * @mbggenerated
     */
    public void setVoltagec(String voltagec) {
        this.voltagec = voltagec == null ? null : voltagec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.electricA
     *
     * @return the value of telemetry_switch_pump.electricA
     *
     * @mbggenerated
     */
    public String getElectrica() {
        return electrica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.electricA
     *
     * @param electrica the value for telemetry_switch_pump.electricA
     *
     * @mbggenerated
     */
    public void setElectrica(String electrica) {
        this.electrica = electrica == null ? null : electrica.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.electricB
     *
     * @return the value of telemetry_switch_pump.electricB
     *
     * @mbggenerated
     */
    public String getElectricb() {
        return electricb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.electricB
     *
     * @param electricb the value for telemetry_switch_pump.electricB
     *
     * @mbggenerated
     */
    public void setElectricb(String electricb) {
        this.electricb = electricb == null ? null : electricb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.electricC
     *
     * @return the value of telemetry_switch_pump.electricC
     *
     * @mbggenerated
     */
    public String getElectricc() {
        return electricc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.electricC
     *
     * @param electricc the value for telemetry_switch_pump.electricC
     *
     * @mbggenerated
     */
    public void setElectricc(String electricc) {
        this.electricc = electricc == null ? null : electricc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.userNumber
     *
     * @return the value of telemetry_switch_pump.userNumber
     *
     * @mbggenerated
     */
    public String getUsernumber() {
        return usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.userNumber
     *
     * @param usernumber the value for telemetry_switch_pump.userNumber
     *
     * @mbggenerated
     */
    public void setUsernumber(String usernumber) {
        this.usernumber = usernumber == null ? null : usernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.icCard
     *
     * @return the value of telemetry_switch_pump.icCard
     *
     * @mbggenerated
     */
    public String getIccard() {
        return iccard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.icCard
     *
     * @param iccard the value for telemetry_switch_pump.icCard
     *
     * @mbggenerated
     */
    public void setIccard(String iccard) {
        this.iccard = iccard == null ? null : iccard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.balance
     *
     * @return the value of telemetry_switch_pump.balance
     *
     * @mbggenerated
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.balance
     *
     * @param balance the value for telemetry_switch_pump.balance
     *
     * @mbggenerated
     */
    public void setBalance(String balance) {
        this.balance = balance == null ? null : balance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.waterConsumption
     *
     * @return the value of telemetry_switch_pump.waterConsumption
     *
     * @mbggenerated
     */
    public String getWaterconsumption() {
        return waterconsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.waterConsumption
     *
     * @param waterconsumption the value for telemetry_switch_pump.waterConsumption
     *
     * @mbggenerated
     */
    public void setWaterconsumption(String waterconsumption) {
        this.waterconsumption = waterconsumption == null ? null : waterconsumption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.electricityConsumption
     *
     * @return the value of telemetry_switch_pump.electricityConsumption
     *
     * @mbggenerated
     */
    public String getElectricityconsumption() {
        return electricityconsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.electricityConsumption
     *
     * @param electricityconsumption the value for telemetry_switch_pump.electricityConsumption
     *
     * @mbggenerated
     */
    public void setElectricityconsumption(String electricityconsumption) {
        this.electricityconsumption = electricityconsumption == null ? null : electricityconsumption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.useTime
     *
     * @return the value of telemetry_switch_pump.useTime
     *
     * @mbggenerated
     */
    public String getUsetime() {
        return usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.useTime
     *
     * @param usetime the value for telemetry_switch_pump.useTime
     *
     * @mbggenerated
     */
    public void setUsetime(String usetime) {
        this.usetime = usetime == null ? null : usetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.startTime
     *
     * @return the value of telemetry_switch_pump.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.startTime
     *
     * @param starttime the value for telemetry_switch_pump.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.endTime
     *
     * @return the value of telemetry_switch_pump.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.endTime
     *
     * @param endtime the value for telemetry_switch_pump.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.consumption
     *
     * @return the value of telemetry_switch_pump.consumption
     *
     * @mbggenerated
     */
    public String getConsumption() {
        return consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.consumption
     *
     * @param consumption the value for telemetry_switch_pump.consumption
     *
     * @mbggenerated
     */
    public void setConsumption(String consumption) {
        this.consumption = consumption == null ? null : consumption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.type
     *
     * @return the value of telemetry_switch_pump.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.type
     *
     * @param type the value for telemetry_switch_pump.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.comtrol
     *
     * @return the value of telemetry_switch_pump.comtrol
     *
     * @mbggenerated
     */
    public String getComtrol() {
        return comtrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.comtrol
     *
     * @param comtrol the value for telemetry_switch_pump.comtrol
     *
     * @mbggenerated
     */
    public void setComtrol(String comtrol) {
        this.comtrol = comtrol == null ? null : comtrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telemetry_switch_pump.createTime
     *
     * @return the value of telemetry_switch_pump.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telemetry_switch_pump.createTime
     *
     * @param createtime the value for telemetry_switch_pump.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_switch_pump
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", telemetryaddress=").append(telemetryaddress);
        sb.append(", centeradress=").append(centeradress);
        sb.append(", password=").append(password);
        sb.append(", serialnumber=").append(serialnumber);
        sb.append(", fuctioncode=").append(fuctioncode);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", typecode=").append(typecode);
        sb.append(", observationtime=").append(observationtime);
        sb.append(", status=").append(status);
        sb.append(", cumulativeflowrate=").append(cumulativeflowrate);
        sb.append(", cumulativeelectricityrate=").append(cumulativeelectricityrate);
        sb.append(", voltagea=").append(voltagea);
        sb.append(", voltageb=").append(voltageb);
        sb.append(", voltagec=").append(voltagec);
        sb.append(", electrica=").append(electrica);
        sb.append(", electricb=").append(electricb);
        sb.append(", electricc=").append(electricc);
        sb.append(", usernumber=").append(usernumber);
        sb.append(", iccard=").append(iccard);
        sb.append(", balance=").append(balance);
        sb.append(", waterconsumption=").append(waterconsumption);
        sb.append(", electricityconsumption=").append(electricityconsumption);
        sb.append(", usetime=").append(usetime);
        sb.append(", starttime=").append(starttime);
        sb.append(", endtime=").append(endtime);
        sb.append(", consumption=").append(consumption);
        sb.append(", type=").append(type);
        sb.append(", comtrol=").append(comtrol);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}