package com.dyzhsw.cardcontrol.mapper;

import com.dyzhsw.cardcontrol.dto.Configuration;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration
     *
     * @mbggenerated
     */
    int insert(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration
     *
     * @mbggenerated
     */
    int insertSelective(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration
     *
     * @mbggenerated
     */
    Configuration selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Configuration record);

    List<Configuration> selectConfigeration(@Param("fuctionCode") String fuctionCode, @Param("telemetryAddress") String telemetryAddress, @Param("centerAdress") String centerAdress, @Param("startTime") String startTime, @Param("endTime") String endTime);
}