package com.dyzhsw.cardcontrol.mapper;

import com.dyzhsw.cardcontrol.dto.equipment;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface equipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    int insert(equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    int insertSelective(equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    equipment selectBytelemetryAddress(String telemetryAddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(equipment record);


    List<equipment> getEquipmentPage();
}