package com.dyzhsw.cardcontrol.mapper;

import com.dyzhsw.cardcontrol.dto.OutMessage;
import com.dyzhsw.cardcontrol.dto.StationTime;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface OutMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_message
     *
     * @mbggenerated
     */
    int insert(OutMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_message
     *
     * @mbggenerated
     */
    int insertSelective(OutMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_message
     *
     * @mbggenerated
     */
    OutMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OutMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OutMessage record);

    List<OutMessage> selectOutMessage(@Param("fuctionCode") String fuctionCode, @Param("telemetryAddress") String telemetryAddress, @Param("centerAdress") String centerAdress, @Param("startTime") Date startTime, @Param("endTime") Date endTime);

}