package com.dyzhsw.cardcontrol.mapper;

import com.dyzhsw.cardcontrol.dto.StationModify;
import com.dyzhsw.cardcontrol.dto.SwitchPump;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface StationModifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_modify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_modify
     *
     * @mbggenerated
     */
    int insert(StationModify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_modify
     *
     * @mbggenerated
     */
    int insertSelective(StationModify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_modify
     *
     * @mbggenerated
     */
    StationModify selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_modify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationModify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_modify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationModify record);

    List<StationModify> selectStationModify(@Param("fuctionCode") String fuctionCode, @Param("telemetryAddress") String telemetryAddress, @Param("centerAdress") String centerAdress, @Param("startTime") String startTime, @Param("endTime") String endTime);

}