package com.dyzhsw.cardcontrol.mapper;

import com.dyzhsw.cardcontrol.dto.StationTime;
import com.dyzhsw.cardcontrol.dto.SwitchPump;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface StationTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_time
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_time
     *
     * @mbggenerated
     */
    int insert(StationTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_time
     *
     * @mbggenerated
     */
    int insertSelective(StationTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_time
     *
     * @mbggenerated
     */
    StationTime selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationTime record);

    List<StationTime> selectStationTime(@Param("fuctionCode") String fuctionCode, @Param("telemetryAddress") String telemetryAddress, @Param("centerAdress") String centerAdress, @Param("startTime") String startTime, @Param("endTime") String endTime);

}