package com.dyzhsw.cardcontrol.mapper;

import com.dyzhsw.cardcontrol.dto.StationAdd;
import com.dyzhsw.cardcontrol.dto.StationClock;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface StationClockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_clock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_clock
     *
     * @mbggenerated
     */
    int insert(StationClock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_clock
     *
     * @mbggenerated
     */
    int insertSelective(StationClock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_clock
     *
     * @mbggenerated
     */
    StationClock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_clock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationClock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_clock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationClock record);

    List<StationClock> selectStationClock(@Param("fuctionCode") String fuctionCode, @Param("telemetryAddress") String telemetryAddress, @Param("centerAdress") String centerAdress, @Param("startTime") String startTime, @Param("endTime") String endTime);

}