package com.dyzhsw.cardcontrol.mapper;

import com.dyzhsw.cardcontrol.dto.StationAdd;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface StationAddMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_add
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_add
     *
     * @mbggenerated
     */
    int insert(StationAdd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_add
     *
     * @mbggenerated
     */
    int insertSelective(StationAdd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_add
     *
     * @mbggenerated
     */
    StationAdd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_add
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationAdd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telemetry_station_add
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationAdd record);

    List<StationAdd> selectStationAdd(@Param("fuctionCode") String fuctionCode, @Param("telemetryAddress") String telemetryAddress, @Param("centerAdress") String centerAdress, @Param("startTime") String startTime, @Param("endTime") String endTime);

}