
server:
  port: 8761
  
spring:
  application:
    name: basic-registry1

eureka:
  instance:
    hostname: 192.168.40.127    
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
logging:
  file: logs/basic-registry.log
  level:
    root: warn
  
